spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentmanager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html


mybatis:
  type-aliases-package: com.wdd.studentmanager.domain
  mapper-locations: classpath:mapper/*.xml


#spring.thymeleaf.servlet.content-type=text/html
#spring.thymeleaf.mode: HTML
#spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#声明thymeleaf使用非严格的html。
#spring.thymeleaf.check-template=true
#spring.thymeleaf.check-template-location=true
#spring.thymeleaf.mode=LEGACYHTML5
